name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  build_dir: "build"
  config: "Release"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            cuda_os: "ubuntu2004"
            cuda: "11.6.2"
            cuda_alt: "11-6"
            cuda_path: "11.6"
            cuda_version_num: "510.47.03-1"
            gcc: 10
        #  - os: ubuntu-20.04
        #    cuda_os: "ubuntu2004"
        #    cuda: "11.8.0"
        #    cuda_alt: "11-8"
        #    cuda_version_num: "520.61.05-1"
        #    gcc: 10
        #  - os: ubuntu-18.04
        #    cuda: "10.1"
        #    gcc: 8

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Install CUDA
      run: |
        cd
        wget https://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.cuda_os }}/x86_64/cuda-${{ matrix.cuda_os }}.pin
        sudo mv cuda-${{ matrix.cuda_os }}.pin /etc/apt/preferences.d/cuda-repository-pin-600
        wget https://developer.download.nvidia.com/compute/cuda/${{ matrix.cuda }}/local_installers/cuda-repo-${{ matrix.cuda_os }}-${{ matrix.cuda_alt  }}-local_${{ matrix.cuda }}-${{ matrix.cuda_version_num }}_amd64.deb
        sudo dpkg -i cuda-repo-${{ matrix.cuda_os }}-${{ matrix.cuda_alt  }}-local_${{ matrix.cuda }}-${{ matrix.cuda_version_num }}_amd64.deb
        sudo apt-key add /var/cuda-repo-${{ matrix.cuda_os }}-${{ matrix.cuda_alt }}-local/7fa2af80.pub
        sudo apt-get update
        sudo apt-get -y install cuda
        export PATH=/usr/local/cuda-${{ matrix.cuda_path }}/bin${PATH:+:${PATH}}
        sudo reboot
        
    
  #  - name: Install CUDA Samples
  #    run: |
  #      git clone https://github.com/NVIDIA/cuda-samples.git
  #      cd cuda-samples
  #      make
    
    # Specify the correct host compilers
    - name: Install/Select gcc and g++ 
      run: |
        cd
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
        
    - name: Install/Select GTest
      run: |
        cd
        sudo apt-get install libgtest-dev 
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt 
        sudo make 
        sudo cp ./lib/libgtest*.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a 
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
        
    - name: Configure cmake
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system

    - name: Build everything else
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --target all --verbose -j `nproc`
